data:
  path: "../data/Residential-Building-Data-Set.xlsx"
  repo: 
  version: v1
  test_size: 0.3
  random_state: 42
  data_format: xlsx
  sheet_name: Data

model:
  alpha: 1
  l1_ratio: 0.1
  max_iter: 1000
  selection: random

evaluation:
  split_strategy: train_test_split
  n_splits: 5
  shuffle: True

config:
  random_seed: 42
  logging_level: WARN